# Generated by Django 6.0.7 on 2026-07-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
    ]
