# Generated by Django 6.0.7 on 2026-08-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('registration', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'email')},
        ),
    ]
