# Generated by Django 6.0.7 on 2026-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_category_description_category_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(default='CAT-01', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
