# Generated by Django 6.0.7 on 2026-09-03 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_qr',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_qrcodes/'),
        ),
    ]
